title: plainfootball
author: mxdws
email:
description: Simple football fixtures, scores and standings.

# social links
twitter_username: zonalmartin
github_username:  mxdws
rss: rss

sass:
    sass_dir: _sass
    style: compressed

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
